version: '2'

volumes:
  onisrc:

services:
  rdbms:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=openoni
      - MYSQL_USER=openoni
      - MYSQL_PASSWORD=openoni
    volumes:
      - ./conf/mysql/:/etc/mysql/conf.d:ro
  solr:
    image: solr:8-slim
    command:
      - solr-precreate
      - openoni
  test:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/src/openoni:ro
      - onisrc:/opt/openoni
    depends_on:
      - rdbms
      - solr
    environment:
      - ONLY_RUN_TESTS=1
      - APP_URL
