# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_copyright_lccndatecopyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='notes',
            field=models.TextField(help_text='852$z', null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='medium',
            field=models.CharField(help_text='245$h field', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='uri',
            field=models.URLField(help_text='856$u', max_length=500, null=True),
        ),
    ]
