# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191114_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='released',
        ),
    ]
