# Generated by Django 3.2.12 on 2023-05-18 17:21

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_batch_released'),
    ]

    # This is an absolutely awful hack, but this migration is pretty specific to mysql
    settings_module = os.getenv('DJANGO_SETTINGS_MODULE')
    if settings_module == 'onisite.test_settings':
        operations = []
    else:
        operations = [
            migrations.RunSQL('SET FOREIGN_KEY_CHECKS=0'),
            migrations.RunSQL('ALTER DATABASE openoni CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'),
            migrations.RunSQL('ALTER TABLE `core_languagetext` CHANGE `text` `text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL'),
            migrations.RunSQL('SET FOREIGN_KEY_CHECKS=1'),
        ]
