# Generated by Django 3.2.12 on 2023-05-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_batch_released'),
    ]

    operations = [
        migrations.RunSQL('SET FOREIGN_KEY_CHECKS=0'),
        migrations.RunSQL('ALTER DATABASE openoni CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'),
        migrations.RunSQL('ALTER TABLE `core_languagetext` CHANGE `text` `text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL'),
        migrations.RunSQL('SET FOREIGN_KEY_CHECKS=1'),
    ]
