# Generated by Django 3.2.12 on 2023-05-18 17:21

from django.db import migrations

def apply_utf8_fix(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        return

    schema_editor.execute('SET FOREIGN_KEY_CHECKS=0')
    schema_editor.execute('ALTER DATABASE openoni CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci')
    schema_editor.execute('ALTER TABLE `core_languagetext` CHANGE `text` `text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL')
    schema_editor.execute('SET FOREIGN_KEY_CHECKS=1')

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0006_remove_batch_released'),
    ]

    operations = [
        migrations.RunPython(apply_utf8_fix, migrations.RunPython.noop)
    ]
