# Generated by Django 3.2.12 on 2023-07-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_utf8fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
