# Generated by Django 3.2.12 on 2023-07-30 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_batch_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Succeeded'), (3, 'Failed')])),
                ('type', models.IntegerField(choices=[(1, 'Load Batch'), (2, 'Purge Batch')])),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'info', '-last_modified'], name='core_job_status_8c83e8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['type', 'info', '-last_modified'], name='core_job_type_77d818_idx'),
        ),
    ]
