FROM ubuntu:trusty
MAINTAINER Mark Cooper <mark.cooper@lyrasis.org>

ENV DJANGO_SETTINGS_MODULE openoni.settings

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
  apache2 \
  ca-certificates \
  gcc \
  git \
  graphicsmagick \
  libapache2-mod-wsgi \
  libmysqlclient-dev \
  libxml2-dev \
  libxslt-dev \
  libjpeg-dev \
  mysql-client \
  python-dev \
  python-virtualenv \
  supervisor

RUN a2enmod cache cache_disk expires rewrite proxy_http
RUN mkdir -p /var/cache/httpd/mod_disk_cache
RUN chown -R www-data:www-data /var/cache/httpd
ADD apache/openoni.conf /etc/apache2/sites-available/openoni-orig.conf
RUN a2dissite 000-default.conf

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
VOLUME /opt/openoni
WORKDIR /opt/openoni

ADD pip-install.sh /
ADD load_batch.sh /
ADD purge_batch.sh /
ADD collect_static.sh /
ADD startup.sh /
ADD test.sh /
ADD django_admin /
ADD openoni.ini /etc/openoni.ini.orig

RUN chmod u+x /*.sh
RUN chmod u+x /django_admin

EXPOSE 80
CMD ["/startup.sh"]
