####################################################################
# DJANGO 1.9 DEFAULT SETTINGS
####################################################################
"""
Django settings for onisite project.

Generated by 'django-admin startproject' using Django 1.9.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onisite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onisite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'


####################################################################
# PRIVATE CONSTANTS
####################################################################
# 'Private' aliases for seconds in a day and week
_ONEDAY = 60 * 60 * 24
_ONEWEEK = _ONEDAY * 7


####################################################################
# DJANGO CUSTOMIZATIONS
####################################################################
# Hosts/domain names valid for this site
# Should be overridden in settings_local.py, especially for production
# TODO: Enable overriding by /etc/openoni.ini
ALLOWED_HOSTS = ['*']


CACHES = {
    'default': {
        # Development
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache'

        # Production
        #'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        #'LOCATION': '/var/tmp/django_cache',
        #'TIMEOUT': _ONEWEEK * 8
    }
}


# Overridden in settings_local.py or /etc/openoni.ini
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'rdbms',
        'NAME': 'openoni',
        'USER': 'openoni',
        'PASSWORD': 'openoni',
    }
}

# List of configuration classes / app packages in order of priority (i.e., the
# first item in the list has final say when collisions occur)
INSTALLED_APPS = (
    # Default
#    'django.contrib.admin',
#    'django.contrib.auth',
#    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # OpenONI
    'django.contrib.humanize',  # Added to make data more human-readable
    'themes.default',
    'core',
)

# Suggested order: https://docs.djangoproject.com/en/1.9/ref/middleware/#middleware-ordering
MIDDLEWARE_CLASSES = (
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.TooBusyMiddleware',                               # OpenONI
    'django.middleware.http.ConditionalGetMiddleware',                 # OpenONI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.auth.middleware.AuthenticationMiddleware',
#    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

# Site id differentiates DB data if multiple sites use the same database
SITE_ID = 1

# Use cache with storing static files; e.g., CSS, images, etc.
# Development (Default)
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
# Production
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'

# URL prepended to static file paths; Must include trailing slash
STATIC_URL = '/media/'

# Directory path to static files
STATIC_ROOT = os.path.join(BASE_DIR, '.static-media')

# Template configuration (1.8+)
TEMPLATES = [
    {
        # Whether engine looks inside application directories for templates
        'APP_DIRS': True,

        # Template engine
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Template-containing directories
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],

        'OPTIONS': {
            # https://docs.djangoproject.com/en/1.9/topics/templates/#module-django.template.backends.django
            
            # Callables which alter the request context
            'context_processors': [
                # Default
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
#                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # OpenONI
                'django.template.context_processors.csrf',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'core.context_processors.extra_request_info',
                'core.context_processors.newspaper_info',
            ],
        },
    },
]


####################################################################
# 3RD-PARTY LIB SETTINGS
####################################################################


####################################################################
# DEFAULT OPEN-ONI SETTINGS
####################################################################

# Should be turned on in production.  TODO: this should probably drive the
# DEBUG setting, at least forcing it to be off when IS_PRODUCTION is true.  We
# should also make this overrideable in the INI file.
IS_PRODUCTION = False

LOG_LOCATION = '/opt/openoni/log/'

# Public URLs to the image server endpoints
#
# These must be overridden to point to the image server.  They may be set to
# the same value, but they're kept apart to allow for having static thumbnails,
# thumbnail caching separated from resize caching, etc.  Thumbnails are a much
# smaller subset of possible images and therefore benefit a great deal from
# being cached and/or pregenerated.
RESIZE_SERVER = 'http://example.com/images/iiif'
TILE_SERVER = 'http://example.com/images/iiif'

# How big should thumbnails be?
THUMBNAIL_WIDTH = 240

# These determine the life of various caches (via cache_page)
DEFAULT_TTL_SECONDS = _ONEDAY
PAGE_IMAGE_TTL_SECONDS = _ONEWEEK * 2
API_TTL_SECONDS = 60 * 60  # 1 hour
FEED_TTL_SECONDS = _ONEWEEK

# Turn this on to allow using tiff files for serving images.  Much faster than
# JP2s if you don't have Aware, but significantly more memory-intense.
USE_TIFF = False

# Number of processes in system run queue averaged over last minute beyond which
# OpenONI will return a 'Server Too Busy' response; If unsure, leave at default
# Requires core.middleware.TooBusyMiddleware in MIDDLEWARE_CLASSES
TOO_BUSY_LOAD_AVERAGE = 64

# URL to the Solr server.  This should be overridden in settings_local.py or
# else /etc/openoni.ini.
SOLR = 'http://localhost:8983/solr'

# Languages solr uses
SOLR_LANGUAGES = (
    'ara',
    'bul',
    'cze',
    'dan',
    'ger',
    'gre',
    'eng',
    'spa',
    'baq',
    'per',
    'fin',
    'fre',
    'gle',
    'hin',
    'hun',
    'arm',
    'ind',
    'ita',
    'jpn',
    'lav',
    'dut',
    'nor',
    'por',
    'rum',
    'rus',
    'swe',
    'tha',
    'tur',
)

# Absolute path on disk to the data directory
STORAGE = '/opt/openoni/data/'

# URL path to the data directory
STORAGE_URL = '/data/'

# If LC is down, we've mirrored a *lot* of MARC records - just copy the line
# below into settings_local.py and uncomment it:
# MARC_RETRIEVAL_URLFORMAT = 'https://raw.githubusercontent.com/open-oni/marc-mirror/master/marc/%s/marc.xml'
MARC_RETRIEVAL_URLFORMAT = 'https://chroniclingamerica.loc.gov/lccn/%s/marc.xml'
#MARC_RETRIEVAL_URLFORMAT = 'http://localhost/media/marc/%s/marc.xml'

# Various storage subdirectories
BATCH_STORAGE = os.path.join(STORAGE, 'batches')
OCR_DUMP_STORAGE = os.path.join(STORAGE, 'ocr')
COORD_STORAGE = os.path.join(STORAGE, 'word_coordinates')
TEMP_TEST_DATA = os.path.join(STORAGE, 'temp_test_data')

# List of breadcrumbs that will be shown on all pages
BASE_CRUMBS = [{'label':'Home', 'href': '/'}]

# BASE_URL is the URL at which this site is hosted, e.g.,
# http://oregonnews.uoregon.edu.  If this isn't set in the INI file, it *must*
# be set in settings_local.py.  Leaving it at the default will not work for
# production or demoing purposes.
#
# NOTE: as of now this can NOT include any path elements!
BASE_URL = 'http://localhost'

# SITE_TITLE that will be used for display purposes throughout app
# PROJECT_NAME may be the same as SITE_TITLE but can be used
# for longer descriptions that will only show up occasionally
# Example 'Open ONI' for most headers, 'Open Online Newspapers Initiative'
# for introduction / about / further information / etc
# Both should be overridden in settings_local.py
SITE_TITLE = 'Open ONI'
PROJECT_NAME = 'Open Online Newspapers Initiative'
